curated/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

urlpatterns = [
    # django admin
    path('admin/', admin.site.urls),

    # wagtail
    path('cms/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's serving mechanism
    path('', include(wagtail_urls)),
    
    path("accounts/", include("django.contrib.auth.urls")),

]

# This will only run in debug mode
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG == True:
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

landscape/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('self_hosted.urls', namespace='self_hosted')),
    path('admin/', admin.site.urls),
    # path("accounts/", include("django.contrib.auth.urls")),

]

# This will only run in debug mode
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG == True:
    urlpatterns += path('__debug__/', include('debug_toolbar.urls')),

self_hosted/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


from .views import AddAppView, UserLogin, home, detail, TagIndexView, AppListView

app_name = 'self-hosted'
urlpatterns = [
    path('', home, name='home'),
    path('self-hosted', AppListView.as_view(), name='app_list'),
    path('<int:app_id>/', detail, name='detail'),
    path('self-hosted/add_app/', AddAppView.as_view() , name="add_app"),
    path('self-hosted/tags/<slug>', TagIndexView.as_view(), name='tagged'),
    path('login/', UserLogin.as_view(), name="login")

]

generic_page/models.py
from tabnanny import verbose
from wagtail.models import Page

# Create your models here.

class GenericPage(Page):

    templates = "generic_page/generic_page.html"

    class Meta:
        verbose_name = "Generic page"
        verbose_name_plural = "Generic pages"

home/models.py
from django.db import models

from wagtail.core.models import Page
from wagtail.fields import RichTextField
from wagtail.admin.edit_handlers import FieldPanel


# Create your models here.

class HomePage(Page):
    """Home page model."""

    templates = "home/home_page.html"

    body = RichTextField(blank=True)

    content_panels = Page.content_panels + [
        FieldPanel("body")
    ]

self_hosted/models.py
from statistics import mode
from django.db import models
from django.forms import FileField
from django.utils import timezone
from django_extensions.db.fields import AutoSlugField
from taggit.managers import TaggableManager

# Create your models here.

def default_time():
    return timezone.now()

class App(models.Model):
    pub_date = models.DateTimeField('date published', default=default_time)
    app_name = models.CharField(max_length=250)
    description = models.TextField(default="", blank=True)
    github_url = models.URLField(default="", blank=True, max_length=300)
    slug = AutoSlugField(populate_from=['app_name'])
    svg_logo = models.FileField(upload_to='logos/', default="",blank=True)

    tags = TaggableManager(blank=True)



    def __str__(self):
        return self.app_name

self_hosted_apps/models.py
from xml.dom import ValidationErr
from django.db import models
from django.forms import ValidationError
from django.core.exceptions import ValidationError

from modelcluster.fields import ParentalKey

from wagtail.models import Page, Orderable
from wagtail.fields import RichTextField
from wagtail.admin.panels import FieldPanel, MultiFieldPanel, InlinePanel
from wagtail.search import index

from wagtailsvg.models import Svg
from wagtailsvg.edit_handlers import SvgChooserPanel



class AppPage(Page):
    """App Page model"""

    templates = "self_hosted_apps/app_page.html"

    github_link = models.URLField(blank=True)
    github_stars = models.IntegerField(blank=True, null=True)
    project_website = models.URLField(blank=True)
    description = RichTextField()

    logo = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    logo_svg = models.ForeignKey(
        Svg,
        related_name='+',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        help_text="SVG"
    )

    def clean(self):
        """Set Validation errors for page fields"""
        
        super().clean()
        
        if self.logo_svg and self.logo:
            raise ValidationError({
                'logo': ValidationError("If possible use SVG Logo"),
                'logo_svg': ValidationError("You can delete the non vector Logo"),
            })

    # Search index configuration

    # search_fields = Page.search_fields + [
    #     index.SearchField('description'),
    #     index.FilterField('date'),
    # ]


    # Editor panels configuration

    content_panels = Page.content_panels + [
        FieldPanel('description', classname="full"),
        FieldPanel('logo'),
        SvgChooserPanel('logo_svg'),
        FieldPanel('github_link'),
        FieldPanel('project_website'),
    ]

    promote_panels = [
        MultiFieldPanel(Page.promote_panels, "Common page configuration"),
        
    ]


    # Parent page / subpage type rules

    parent_page_types = ['AppListPage']
    


# class AppPageRelatedLink(Orderable):
#     page = ParentalKey(AppPage, on_delete=models.CASCADE, related_name='related_links')
#     name = models.CharField(max_length=255)
#     url = models.URLField()

#     panels = [
#         FieldPanel('name'),
#         FieldPanel('url'),
#     ]


class AppListPage(Page):

    subpage_types = ['AppPage']

    subtitle = models.TextField(
        blank=True,
        max_length=500,
    )

    content_panels = Page.content_panels + [
        FieldPanel("subtitle"),
    ]
    
    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request, *args, **kwargs)
        context['apps'] = AppPage.objects.live().public()
        return context

self_hosted/forms.py
from django import forms
from .models import App


class AddAppForm(forms.ModelForm):
    class Meta:
        model = App
        fields = ('app_name', 'description', "github_url", "svg_logo" )

        widgtes = {
            'app_name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'github_url': forms.URLInput(attrs={'class': 'form-control'}),
            'svg_logo': forms.FileInput(attrs={'class': 'form-control'}),
        }

self_hosted/views.py
from django.http import Http404
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.contrib.auth.views import LoginView    
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy

from .models import App
from .forms import AddAppForm
from taggit.models import Tag

# Will add "tags" as context variables in tempaltes
class TagMixin(object):
    def get_context_data(self, **kwargs):
        context = super(TagMixin, self).get_context_data(**kwargs)
        context["tags"] = Tag.objects.all()
        return context
    

def home(request):
    return render(request, "self_hosted/home.html")

def detail(request, app_id):
    app = get_object_or_404(App, pk=app_id)
    return render(request, 'self_hosted/detail.html', {'app': app})

class AddAppView(CreateView):
    model = App
    template_name = "self_hosted/add_app.html"
    form_class = AddAppForm
    success_url = reverse_lazy('self_hosted:app_list')

class AppListView(TagMixin, ListView):
    template_name = "self_hosted/index.html"
    model = App
    paginate_by = '50'
    context_object_name = 'apps'

class TagIndexView(TagMixin, ListView):
    template_name = "self_hosted/index.html"
    model = App
    paginate_by = '50'
    context_object_name = 'apps'

    def get_queryset(self):
        return App.objects.filter(tags__slug=self.kwargs.get('slug'))

class UserLogin(LoginView):
    template_name = "self_hosted/login.html"
    next_page = '/'

curated/templates/base.html
{% load static %}
{% load static wagtailuserbar %}


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Curated-DB</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        {% if UMAMI_KEY %}
        {% else %}
            <script async defer data-website-id="{ UMAMI_KEY }}" src="{ UMAMI_ADDRESS }}"></script>
        {% endif %}
    </head>
    <body>
        <!-- Responsive navbar-->
        {% include 'navbar.html' %}
        <!-- Header-->
        {% include 'header.html' %}
        <!-- Page Content-->
        <section class="pt-4">
        <div class="container px-lg-5">
            <!-- Page Features-->
            <div class="row gx-lg-5">

                {% block content %}
                {% endblock %}

                    </div>      
            </div>

        </section>
        <!-- Footer-->
        {% include 'footer.html' %}
        {% wagtailuserbar %}
    </body>
</html>

curated/templates/footer.html
{% load static %}


<footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="{% static 'js/bootstrap.min.js' %}"></script>

curated/templates/header.html
<header class="py-5">
</header>

curated/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-lg-5">
        <a class="navbar-brand" href="/">Curated-DB</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link" href="#!">Self-Hosted</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
            </ul>
        </div>
    </div>
</nav>

generic_page/templates/generic_page/generic_page.html
{% extends "base.html" %}

{% block content%}

    <div class="row">
        <h1>{{page.title}}</h1>
    </div>


{% endblock content%}

home/templates/home/home_page.html
{% extends "base.html" %}

{% load wagtailcore_tags %}


{% block content %}

<h1>{{ page.title }}</h1>
    
    {{ page.body|richtext }}

{% endblock %}

self_hosted/templates/self_hosted/add_app.html
{% extends "self_hosted/base.html" %}
{% load static %} 
{% block content %}
<div class="container" style="max-width:600px">
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Add apps</h1>
    </div>
    <div class="py-5">
        <div class="row">
            <div class="col-12">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    <div class="mb-3">
                        <label for="id_app_name" class="form-label">App Name</label>
                        <input type="text" name="app_name" maxlength="250" required id="id_app_name" class="form-control">
                    </div>

                    <div class="mb-3">
                        <label for="id_description" class="form-label">Description</label>
                        <textarea class="form-control" id="id_description" name="description"  rows="5"></textarea>
                      </div>

                    <label for="id_github_url" class="form-label">GitHub URL</label>
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon3">https://github.com/user/repository</span>
                        <input type="url" class="form-control" maxlength="250" id="github_url" aria-describedby="basic-addon3">
                    </div>
                    
                    <div class="mb-3">
                        <label for="id_svg_logo" class="form-label">Logo</label>
                        <input name="svg_logo" class="form-control" type="file" id="id_svg_logo">
                    </div>
                    
                    <input type="submit">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

self_hosted/templates/self_hosted/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Curated-DB</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'self_hosted/assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'self_hosted/css/bootstrap.min.css' %}" rel="stylesheet" />
        {% if UMAMI_KEY %}
        {% else %}
            <script async defer data-website-id="{ UMAMI_KEY }}" src="{ UMAMI_ADDRESS }}"></script>
        {% endif %}
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-lg-5">
                <a class="navbar-brand" href="{% url 'self-hosted:home' %}">Curated-DB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'self-hosted:app_list' %}">Self-Hosted</a></li>
                        <li class="nav-item"><a class="nav-link" aria-current="page" href="">Dev & Ops Articles</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="login">Login</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="py-5">
        </header>
        <!-- Page Content-->
        <section class="pt-4">
        <div class="container px-lg-5">
            <!-- Page Features-->
            <div class="row gx-lg-5">

                {% block content %}
                {% endblock %}
                    </div>        
            </div>
        </section>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="{% static 'self_hosted/js/bootstrap.min.js' %}"></script>
    </body>
</html>

self_hosted/templates/self_hosted/detail.html
{% extends 'self_hosted/base.html' %}

{% block content %}

<header class="py-5">
    <div class="container px-lg-5">
        <div class="p-4 p-lg-5 bg-light rounded-3 text-center">
            <div class="m-4 m-lg-5">
                <h1 class="display-5 fw-bold">{{ app }}</h1>
                <p class="fs-4">{{ app.description }}</p>
                <p class="fs-4">{{ app.github_url}}</p>
                <p class="fs-4">{{ app.tags.all}}</p>
                <a class="btn btn-primary btn-lg" href="#!">Call to action</a>
            </div>
        </div>
    </div>
</header>

{% endblock %}

self_hosted/templates/self_hosted/header.html
<header class="py-5">
    <div class="container px-lg-5">
        <div class="p-4 p-lg-5 bg-light rounded-3 text-center">
            <div class="m-4 m-lg-5">
                <h1 class="display-5 fw-bold">A warm welcome!</h1>
                <p class="fs-4">Bootstrap utility classes are used to create this jumbotron since the old component has been removed from the framework. Why create custom CSS when you can use utilities?</p>
                <a class="btn btn-primary btn-lg" href="#!">Call to action</a>
            </div>
        </div>
    </div>
</header>

self_hosted/templates/self_hosted/home.html
{% extends 'self_hosted/base.html' %}

{% block content %}

<div class="container px-lg-5">
    <div class="p-4 p-lg-5 bg-light rounded-3 text-center">
        <div class="m-4 m-lg-5">
            <h1 class="display-5 fw-bold">Hey there fellow nerd! 👋</h1>
            <p class="fs-4">This a curated list differnt things</p>
            <a class="btn btn-primary btn-lg" href="self-hosted">Go to self-hosted</a>
        </div>
    </div>
</div>

    
{% endblock %}

self_hosted/templates/self_hosted/index.html
{% extends 'self_hosted/base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid px-4">
  <h1 class="mt-4">Dashboard</h1>
  <a href="{% url 'self-hosted:add_app'%}" class="link-primary">Add app</a>
  <div class="row row-cols-sm-1 row-cols-md-3 row-cols-lg-3 row-cols-xl-3">

{% if apps %}
{% for app in apps %}
    <div class="col pb-3">
        <div class="card h-100 text-center">
            {% if app.svg_logo %}
                {% comment %} <img src="{{ app.svg_logo.url }}" class="card-img-top img-fluid mx-auto w-25 p-2" alt="..."> {% endcomment %}
            {% else %}
                <img src="{% static 'self_hosted/images/placeholder.svg' %}" class="card-img-top img-fluid mx-auto w-25 p-2" alt="...">
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{ app.app_name}}</h5>
            <p class="card-text">{{ app.description }}</p>
            <a href="{% url 'self-hosted:detail' app.id %}" class="card-link">Details</a>
            <a href="#" class="card-link">To Project</a>
          </div>
          <div class="card-footer">
            <small class="text-muted">Last updated 3 mins ago</small>
          </div>
        </div>
    </div>
{% endfor %}
{% else %}
<p>No apps yet.</p>
{% endif %}
  </div>

  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
  
        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
  
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
  </div>

</div>


{% endblock %}

self_hosted/templates/self_hosted/login.html
<html>
    <head>
        <title>LoginView</title>
        
    </head>

    <body>
<form method="POST">{% csrf_token %}
    
<!-- form variable -->    
 {{ form.as_p }} 

  <input type="submit" name="sumbit">
</form>
    </body>

</html>

self_hosted_apps/templates/self_hosted_apps/app_list_page.html
{% extends "base.html" %}
{% load static wagtailuserbar %}
{% load wagtailcore_tags %}
{% load wagtailimages_tags %}


{% block content%}

<h1>{{page.title}}</h1>
{%if page.subtitle %}
    <p>{{page.subtitle}}</p>
{% endif %}

<div class="row row-cols-1 row-cols-md-2 g-4">
  {% if apps %}
  {% for app in apps %}
    <div class="col pb-3">
      <div class="card h-100 text-center">
        {% if app.logo_svg %}
          <img src="{{app.logo_svg.url}}" class="card-img-top img-fluid mx-auto w-25 p-2" alt="...">
        {% elif app.logo %}
          {% image app.logo width-3000 as card_img%}
          <img src="{{card_img.url}}" class="card-img-top img-fluid mx-auto w-25 p-2" alt="...">
        {% else %}
          <img src="{% static 'images/placeholder_300x300.svg' %}" class="card-img-top img-fluid mx-auto w-25 p-2" alt="...">
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{app.title}}</h5>
          <p class="card-text">{{app.description|richtext}}</p>
          <a href="{{ app.url}}" class="btn btn-primary">More Details</a>
        </div>
        <div class="card-footer">
          <small class="text-muted">GitHub Stars 5</small>
        </div>
      </div>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No apps yet.</p>
{% endif %}

{% endblock %}

self_hosted_apps/templates/self_hosted_apps/app_page.html
{% extends "base.html" %}
{% load wagtailimages_tags %}
{% load wagtailcore_tags %}


{% block content %}

{{ page.title}}

{{ page.description|richtext }}

{% endblock %}